module repeat_loop();
  bit[7:0]a;
  int i;
  initial begin
    $display("------------------------REPEAT LOOP---------------------------");
    repeat (20)begin
      a+=10;
      $display("THE VALUE OF A IN INTERATION%0d =%0d",i,a);
      i++;
    end
  end
endmodule

/*
OUTPUT:
------------------------REPEAT LOOP---------------------------
THE VALUE OF A IN INTERATION0 =10
THE VALUE OF A IN INTERATION1 =20
THE VALUE OF A IN INTERATION2 =30
THE VALUE OF A IN INTERATION3 =40
THE VALUE OF A IN INTERATION4 =50
THE VALUE OF A IN INTERATION5 =60
THE VALUE OF A IN INTERATION6 =70
THE VALUE OF A IN INTERATION7 =80
THE VALUE OF A IN INTERATION8 =90
THE VALUE OF A IN INTERATION9 =100
THE VALUE OF A IN INTERATION10 =110
THE VALUE OF A IN INTERATION11 =120
THE VALUE OF A IN INTERATION12 =130
THE VALUE OF A IN INTERATION13 =140
THE VALUE OF A IN INTERATION14 =150
THE VALUE OF A IN INTERATION15 =160
THE VALUE OF A IN INTERATION16 =170
THE VALUE OF A IN INTERATION17 =180
THE VALUE OF A IN INTERATION18 =190
THE VALUE OF A IN INTERATION19 =200
           V C S   S i m u l a t i o n   R e p o r t 
*/
